### ISSUE TITLE
Non-Default DPI Values

### ISSUE THREAD

**Issue by IT-Emilio** [sensboston/AdjustDisplay#1]
I’ve just downloaded your code and it works vey well, but I need to scale the screen to a non-default DPI value (130% or 135%).
I’m not sure I understood all the code and methods you used to perform the screen scaling, and I’m not able to achieve my goal by myself...
Is it possible to do this?

Best regards,
Emilio

**Comment by sensboston** [comment]
It looks like Windows doesn't supports a free scaling.
Available values are: 100,125,150,175,200,225,250,300,350,400,450,500
So, it's impossible.
